version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  verbose:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s() - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: logs/bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: verbose
    filename: logs/errors.log
    maxBytes: 5242880  # 5MB
    backupCount: 3
    encoding: utf8

  telegram_handler:
    class: src.utils.telegram_logger.TelegramLogsHandler
    level: CRITICAL
    formatter: standard
    token: ${TELEGRAM_BOT_TOKEN}
    chat_id: ${TELEGRAM_LOG_CHAT_ID}

loggers:
  data:
    level: DEBUG
    handlers: [file_handler, console]
    propagate: false

  trading:
    level: INFO
    handlers: [file_handler, console, error_handler]
    propagate: false

  strategy:
    level: DEBUG
    handlers: [file_handler]
    propagate: false

  risk:
    level: INFO
    handlers: [file_handler, console, error_handler]
    propagate: false

  telegram:
    level: INFO
    handlers: [console]
    propagate: false

  api:
    level: WARNING
    handlers: [file_handler, error_handler]
    propagate: false

root:
  level: INFO
  handlers: [console, file_handler, error_handler]